name: Code Review

on: [pull_request]

jobs:

  # -- LINT -------------------------------------------------------------------
  tflint:
    name: Code Review - TFlint
    runs-on: ubuntu-latest

    steps:
      - name: Harden GitHub Actions Runner
        uses: step-security/harden-runner@f8b229487278099721572481264761b1d4fdd530
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@ed3a0531877aca392eb870f440d9ae7aba83a6bd # tag=v1.4.0
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init

      # Run TFLint
      - name: tflint with reviewdog output on the PR
        uses: reviewdog/action-tflint@aa45c856f2dec0fbbf5ca56c3e494059a021f88f # v1.17.3

  # -- SECURITY ---------------------------------------------------------------
  tfsec:
    name: Code Review - TFSec
    runs-on: ubuntu-latest

    steps:
      - name: Harden GitHub Actions Runner
        uses: step-security/harden-runner@f8b229487278099721572481264761b1d4fdd530
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      # Run TFSec
      - name: Run tfsec with reviewdog output on the PR
        uses: reviewdog/action-tfsec@c33e075b53fed70183e46124801ff934b5c5ff8b # v1.15.2
