name: Terraform

on: [push]

jobs:

  # -- TESTS ------------------------------------------------------------------
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Harden GitHub Actions Runner
        uses: step-security/harden-runner@6c61cb4fea1342b19f1b0e954c364bdfb464afa8
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@ed3a0531877aca392eb870f440d9ae7aba83a6bd # tag=v1.4.0
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: apply
        run: terraform plan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # -- SAST SCAN --------------------------------------------------------------
  code-security:
    name: Code Security
    runs-on: ubuntu-latest
    needs: tests
    # Skip any PR created by dependabot to avoid permission issues
    if: (github.actor != 'dependabot[bot]')

    steps:
      - name: Harden GitHub Actions Runner
        uses: step-security/harden-runner@6c61cb4fea1342b19f1b0e954c364bdfb464afa8
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Perform Scan
        uses: ShiftLeftSecurity/scan-action@master

        env:
          WORKSPACE: https://github.com/${{ github.repository }}/blob/${{ github.sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SCAN_ANNOTATE_PR: true

      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: reports
          path: reports

  # -- DOCUMENTATION ----------------------------------------------------------
  documentation:
    name: Documentation
    runs-on: ubuntu-latest
    needs: tests
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Harden GitHub Actions Runner
        uses: step-security/harden-runner@6c61cb4fea1342b19f1b0e954c364bdfb464afa8
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          ref: 'main' # Force checkout of main branch to avoid caching from previous jobs

      - name: Terraform Docs
        uses: terraform-docs/gh-actions@f6d59f89a280fa0a3febf55ef68f146784b20ba0 # tag=v1.0.0
        with:
          working-dir: .
          output-file: USAGE.md
          output-method: inject
          git-push: "true"
          git-commit-message: "chore(docs): update Terraform docs"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }} # use a different GITHUB_TOKEN to run commit on protected branches

  # -- RELEASE ----------------------------------------------------------------
  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - code-security
      - documentation
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Harden GitHub Actions Runner
        uses: step-security/harden-runner@6c61cb4fea1342b19f1b0e954c364bdfb464afa8
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          ref: 'main' # Force checkout of main branch to avoid caching from previous jobs
          persist-credentials: false

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@8f6ceb9d5aae5578b1dcda6af00008235204e7fa # v3.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }} # use a different GITHUB_TOKEN to run commit on protected branches
